### ISSUE TITLE
MSBuild integration

### ISSUE THREAD

**Issue by adamralph** [adamralph/min-ver#3]
Essentially, making this work: https://github.com/adamralph/min-ver#quick-start

- [x] most of the work
- [x] [add the targets file to MSBuildAllProjects](https://github.com/adamralph/min-ver/issues/3#issuecomment-433724484)
- [x] ~[suppress the target for design-time builds](https://github.com/adamralph/min-ver/issues/3#issuecomment-433724484)~ - _moved to https://github.com/adamralph/min-ver/issues/55_

**Comment by thefringeninja** [comment]
Hate to say it but I think you need an msbuild task here. https://github.com/natemcmaster/Yarn.MSBuild might be an inspiration

**Comment by bording** [comment]
@adamralph There are two main ways you can integrate the logic into MSBuild:

1. Ship a command-line tool of some sort that gets called from an MSBuild target via an `Exec` task. 
2. Create an MSBuild task that can be called from a target

Option 1 means you have to output all the needed values to the console and them parse them back out in your MSBuild targets, which can be messy.

Option 2 still means you could also ship a separate command-line tool if you want (for example as a .NET Core global tool), but the actual logic would be invoked directly as a task, and then you can get all the needed values back as regular properties.

Option 2 might seem like the best option, but there is a caveat here as well. Because you're using LibGit2Sharp, getting an MSBuild task working fully cross-platform is non-trivial. There are platform-specific native binaries that you have to deal with. MSBuild offers no assistance in making sure the correct one is loaded, so you have to handle all of that yourself. At the moment, that would involve some level of RID analysis to choose the correct binary. There are LibGit2Sharp changes coming "soon" that will make all of this more palatable, though.

Invoking a command-line tool instead could leverage .NET Core's ability to load the correct binary for you, so that's one reason that might be better. This is likely to be slower though, and this something needs to be invoked every time you build.

**Comment by thefringeninja** [comment]
I think option 2) is the the most viable. Publish a dotnet cli tool e.g. `dotnet min-ver`. Then, using the technique described here: https://natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/ you could get that to invoke via `dotnet build`.

Also, I don't think slowness is an issue here... normally you would invoke this as part of your CI process, not on your dev machine.

**Comment by bording** [comment]
> I think option 2) is the the most viable. Publish a dotnet cli tool e.g. dotnet min-ver. Then, using the technique described here: https://natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/ you could get that to invoke via dotnet build.

You seem to be mixing things a bit. Option 1 would be the "invoke a command-line" approach, but you wouldn't really be able to tie that to a .NET Core global tool, since there would be no way to ensure the tool was installed.

The link you posted is detailing what I called Option 2, but that doesn't address any of the difficulties around the native libraries.

> Also, I don't think slowness is an issue here... normally you would invoke this as part of your CI process, not on your dev machine.

I disagree. This is something you'll have installed in your project, and it will run as part of your build.

**Comment by thefringeninja** [comment]
Sorry if I wasn't more clear. What I am suggesting is that you can slip in an `<Exec />` task via `obj/$(MSBuildProject).nuget.g.props` into `BeforeBuild` when the nuget package installs the cli tool. And of course this would require Lib2SharpGit to get updated.

**Comment by adamralph** [comment]
I'd like to avoid building an MSBuild task if possible, so right now I'm favouring option 1. I'm hoping it can be as simple as having an executable sitting next to the `targets` file.

I've pushed my initial naive attempt to https://github.com/adamralph/min-ver-sandbox. (All the `MinVer*.*` artifacts are the binaries which result from building this repo.)

If you run `build.cmd`, you can see that MinVer is getting invoked, and it's calculating the version as `0.0.0-alpha.0`, but I've no idea where to go from there.

One obvious problem is that `<Exec ... ConsoleToMsBuild="true">` is picking up both stdout and stderr, even though the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.exec.consoletomsbuild?view=netframework-4.7.2#Microsoft_Build_Tasks_Exec_ConsoleToMSBuild) say that it should only contain look at stdout. All the lines which start with `MinVer: ` are actually in stderr, and only the version number itself is in stdout.

Another thing I've observed is, if I set `<VersionPrefix>` in a `<PropertyGroup>` in the `MinVer` target, it has no effect on the package version, so I guess the target needs to be injected somewhere in the pipeline other than `BeforeTargets="BeforeBuild"`.

The idea is that MinVer will indeed run on _every_ build, not just on a CI server. I'm hoping performance won't be a problem.

**Comment by bording** [comment]
> I'd like to avoid building an MSBuild task if possible, so right now I'm favouring option 1. I'm hoping it can be as simple as having an executable sitting next to the targets file.

Are you okay with requiring the .NET Core SDK to be installed? If not, you'll need to ship two different executables and choose which one to run, either .NET Core or .NET Framework.

>I've pushed my initial naive attempt to https://github.com/adamralph/min-ver-sandbox. (All the MinVer*.* artifacts are the binaries which result from building this repo.)

You'll need to package the `dotnet publish` output when/if you make this work for real. The sandbox repo doesn't have the dependencies.

> One obvious problem is that <Exec ... ConsoleToMsBuild="true"> is picking up both stdout and stderr, even though the docs say that it should only contain stdout. All the lines which start with MinVer: are actually in stderr, and only the version number itself is in stdout.

Take a look at https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2017. It says both standard error and standard output will be captured.

> Another thing I've observed is, if I set <VersionPrefix> in a <PropertyGroup> in the MinVer target, it has no effect on the package version, so I guess the target needs to be injected somewhere in the pipeline other than BeforeTargets="BeforeBuild".

You'll also want to set `PackageVersion` property. Instead of `VersionPrefix`, it's also probably better to just use `Version`. It could also make sense to set some of the other assembly version properties, if you have different things you might want to have in there.

You should also change your for BeforTargets to `BeforeTargets="CoreCompile;GenerateNuspec"`

That ensures the logic is run even with `dotnet pack --no-build`

**Comment by adamralph** [comment]
> Are you okay with requiring the .NET Core SDK to be installed?

Yes, I believe that's an acceptable pre-requisite.

> You'll need to package the dotnet publish output...

Thanks. FWIW, I switched the sandbox to that output in https://github.com/adamralph/min-ver-sandbox/commit/27df9e8bf4aa6f7ebbff28431ca6bae03326255d

> Instead of `VersionPrefix`, it's also probably better to just use `Version`.

If possible, I'd still like to allow the use of `VersionSuffix` to set build metadata, as described in the [quick start](https://github.com/adamralph/min-ver#quick-start), so that's why I was favouring `VersionPrefix`. If that's not possible, then it's not the end of the world.

> You'll also want to set PackageVersion property.

I was hoping to avoid having to set `PackageVersion` explicitly, since I don't set that anywhere currently. I was hoping that `VersionPrefix` could be set at the right time for it, and `VersionSuffix,` to flow into `PackageVersion` automatically, as they currently do.

> It could also make sense to set some of the other assembly version properties, if you have different things you might want to have in there.

Right now I'm hoping to just replace the setting of `VersionPrefix` and nothing else, since that will pick up the major, minor, patch, and pre-release identifiers, and `VersionSuffix` can continue to be used for build metadata via environment variables set on the CI server. I guess the other thing that could be interesting is the commit ID, but currently SourceLink is doing that for me, and tacking it onto the end of what is coming out of `VersionPrefix` and `VersionSuffix` and putting that into `AssemblyInformationalVersion`.

> You should also change your for BeforTargets to BeforeTargets="CoreCompile;GenerateNuspec"

Thanks. I've changed it to that in https://github.com/adamralph/min-ver-sandbox/commit/d08d4dbfc7ae2a0e2f8b3283d798137efe8d0567

So I guess the thing I'm still stuck on is working out which MSBuild incantations I need to get the version number out of stdout and into `VersionPrefix`, at the right time, so that everything else, i.e. putting it together with `VersionSuffix`, getting that into `PackageVersion`, allowing SourceLink to add the commit ID for `AssemblyInformationalVersion`, etc. all "just works". Whether this is achievable or not, I still don't know...

**Comment by adamralph** [comment]
Sadly it looks like `VersionSuffix` can't be used in the way I was hoping. It can't just contain build metadata, since MSBuild adds a hyphen between `VersionPrefix` and `VersionSuffix` when constructing `Version`. So I guess setting `Version` is indeed the right thing to do.

**Comment by bording** [comment]
I'm also not sure you'll be able to avoid setting PackageVersion since Version is being calculated.

It is set here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L28

But since that is in a top-level PropertyGroup, that means it's evaluated before you have a chance to set any version values in targets.

**Comment by bording** [comment]
> can continue to be used for build metadata via environment variables set on the CI server.

Since MSBuild takes all environment variables and turns them into properties, you could still do this by appending that property when you set Version.

**Comment by adamralph** [comment]
> But since that is in a top-level PropertyGroup, that means it's evaluated before you have a chance to set any version values in targets.

Aha, that explains it, thanks! Indeed, if I set `PackageVersion` in my custom target, that _is_ used for the package. And if I inspect the assembly itself, the `Version` which I set in my custom target is being used for assembly version.

> Since MSBuild takes all environment variables and turns them into properties, you could still do this by appending that property when you set Version.

I'd like to avoid giving MinVer knowledge of specific CI environments, but I guess this could be done the other way round: MinVer could look for an environment variable named `MINVER_BUILD_METADATA`.

**Comment by adamralph** [comment]
Woot! I've got it working, but in a very hacky way. It's using a file to capture stdout: https://github.com/adamralph/min-ver-sandbox/commit/3b38e968e6c2cb049a25625ee0fe2d4eb4418b0d

I also threw SourceLink in there just to see how it behaves.

Another thing I've realised now is that `Version` cannot be set to the full version, with the pre-release identifiers. It has to be just the `major.minor.patch`, so the CLI tool will indeed have to output something richer than just a single version string.

**Comment by bording** [comment]
> Another thing I've realised now is that Version cannot be set to the full version, with the pre-release identifiers.

 Why is that? When I was testing it earlier, I was able to do that just fine.

**Comment by adamralph** [comment]
Try loading the assembly into ILSpy. It blows up. 😄 

I guess ILSpy is making an assumption about the `AssemblyVersion` being of the form `n.n.n.n`, which may  not be a CLR-enforced thing, but I think it's still better to play by the conventions.

**Comment by bording** [comment]
When I do that, everything looks fine. AssemblyVersion  is just the numerical portion, as I would expect.

**Comment by adamralph** [comment]
Yeah, on closer inspection, the ILSpy exception stack trace suggests it might just be some other bug:

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   at ICSharpCode.Decompiler.DotNetCorePathFinder..ctor(String parentAssemblyFileName, String targetFrameworkId, String version, ReferenceLoadInfo loadInfo)
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.FindAssemblyFile(AssemblyNameReference name)
   at ICSharpCode.ILSpy.LoadedAssembly.LookupReferencedAssemblyInternal(AssemblyNameReference fullName, Boolean isWinRT)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ICSharpCode.ILSpy.LoadedAssembly.LookupReferencedAssembly(AssemblyNameReference name)
   at ICSharpCode.ILSpy.LoadedAssembly.MyAssemblyResolver.Resolve(AssemblyNameReference name)
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(ModuleDefinition moduleDefinition, DecompilerSettings settings)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass33_0.<DecompileAsync>b__0()
```

How are you seeing `AssemblyVersion`?

**Comment by bording** [comment]
I'm using dotPeek.

**Comment by adamralph** [comment]
OK, I just loaded it into `ildasm` and you're right, it is just the numeric part. Which makes sense, since you can also set a `Version` with pre-release identifiers, and the `AssemblyVersion` comes out correctly.

So I guess the next step is to find a less hacky way than piping stdout to a file and reading it back in.

Also I think [this](https://github.com/adamralph/min-ver#what-if-it-all-goes-wrong) isn't going to work:

> If your tags get into a mess and you can't find a way out, you can temporarily switch off MinVer and switch back to the old way of doing things by simply adding a Version element (or VersionPrefix and VersionSuffix elements) to your project. When you've figured out the problem, remove the element and MinVer will resume active duty.

I think MinVer will have to look for a specific property as an override, e.g. `MinVerVersion`.

**Comment by adamralph** [comment]
I'd quite like the ability to have some MinVer log messages in the output, e.g.

```
  MinVer: Detected { Version: 1.0.0, Commit: 27df9e8bf4aa6f7ebbff28431ca6bae03326255d, Height: 3 }.
  MinVer: 4 commits checked.                                                                       
  MinVer: Using { Version: 1.0.0, Commit: 27df9e8bf4aa6f7ebbff28431ca6bae03326255d, Height: 3 }.   
  MinVer: Calculated 1.1.0-alpha.0.3.                                                              
```

But until now, no actual parsing is required. I'm only using the file because I can't isolate stdout in the `Exec` task. All the above log messages go to stderr.

**Comment by adamralph** [comment]
FTR I found the bug in ILSpy. It didn't like when `AssemblyInformationalVersion` had spaces in it. It had spaces in it because MinVer.Cli.exe is doing a `WriteLine()` to stdout which results in a CRLF. Trimming the output fixed it.

**Comment by adamralph** [comment]
This is what I currently have as a candidate for the package `build` folder: https://github.com/adamralph/min-ver-sandbox/blob/bc083585d4d9b8477b50065c7bd61743d905049d/min-ver-sandbox.csproj#L20-L43

It appears to be fully functional, and it matches the spec implied by the (updated) quick start and FAQ in the README. The only remaining ugliness I'm aware of is the piping of stdout through a file.

**Comment by adamralph** [comment]
Oh, and I tested it on Linux and it worked perfectly.

**Comment by bording** [comment]
> The only remaining ugliness I'm aware of is the piping of stdout through a file.

Yeah, you'll definitely want to fix that up before shipping it!

Overall that is looking good. There are a couple other things that you'll need in there once you actually split it out into it's own targets file, but I can open a PR for those later as needed.

**Comment by adamralph** [comment]
@bording I've pushed an [alpha package](https://www.nuget.org/packages/MinVer/1.0.0-alpha.3) which seems to be fully functional.

Putting aside the ugly stdout hack for a moment, do you know if there's anything else it needs?

**Comment by adamralph** [comment]
> props/targets files should add themselves to MSBuildAllProjects, to ensure any changes to them result in a new build. However, an upcoming change in MSBuild 16 makes this something you no longer want to do. That means you could add something like Microsoft/msbuild#1299 (comment) to both of the targets files.

That sounds like a good idea. Would you like to send a PR?

> Since you aren't currently emitting a type that contains version information (to be able to access those values at runtime) you could consider conditioning the targets to not run as part of a design-time build.

What exactly do you mean by a "design-time build"?

**Comment by bording** [comment]
> That sounds like a good idea. Would you like to send a PR?

I should be able to do that.

> What exactly do you mean by a "design-time build"?

Visual Studio runs a build behind the scenes for various reasons. When it does this it doesn't actually compile the code, but it does figure out what the inputs to csc would be. These are known as design-time builds. It's important to keep this as minimal as possible to avoid causing problems inside VS. If the targets you're adding don't actually have an impact on the compiler input, then you can condition them to be skipped in a design-time build.

Since these targets are only changing version properties, I would think it would be safe to skip them.

**Comment by bording** [comment]
> Putting aside the ugly stdout hack for a moment, do you know if there's anything else it needs?

Take a look at #45 which should solve this.

**Comment by adamralph** [comment]
Thanks @bording, it sounds like suppressing the target for a design-time build is a good idea. Assuming you know how that's done, would you like to send a PR?

**Comment by bording** [comment]
@adamralph I do and I will! 😄

**Comment by adamralph** [comment]
FWIW I've added a checklist to the description of this issue.

**Comment by bording** [comment]
One last thing, are you sure https://github.com/adamralph/min-ver/blob/master/MinVer/MinVer.targets#L24 is needed? It seems like that line could be removed and nothing would change. At that point either MinVerVersion has the correct value, or it needs the build metadata appended. It shouldn't need to be set again.

**Comment by adamralph** [comment]
@bording thanks for looking into the design time build stuff. In that case, let's leave that for now. If you find out more then we can always re-open this issue or open a new one.

You're correct about that line in the targets. I think this was a badly edited copy-paste. I've fixed it in #54.

**Comment by adamralph** [comment]
In the end I decided to spin off the design time build suppression into https://github.com/adamralph/min-ver/issues/55.

**Comment by adamralph** [comment]
Full implementation (#55 notwithstanding) released in [alpha 7](https://www.nuget.org/packages/MinVer/1.0.0-alpha.7).

Thanks @bording for all your help with this. It was invaluable!
