### ISSUE TITLE
Suppress the MinVer target for design time builds

### ISSUE THREAD

**Issue by adamralph** [adamralph/min-ver#55]
_Relates to #3._

_From https://github.com/adamralph/min-ver/issues/3#issuecomment-433735623 by @bording:_

> Visual Studio runs a build behind the scenes for various reasons. When it does this, it doesn't actually compile the code, but it does figure out what the inputs to csc would be. These are known as design-time builds. It's important to keep this as minimal as possible to avoid causing problems inside VS. If the targets you're adding don't actually have an impact on the compiler input, then you can condition them to be skipped in a design-time build.
> 
> Since these targets are only changing version properties, I would think it would be safe to skip them.

_From https://github.com/adamralph/min-ver/issues/3#issuecomment-434117809 by @bording:_

> I also look a look at the design-time build stuff, and it turns out that we need to let this run during design-time builds in order to get project references versioned correctly in the generated nuspec. I'm not entirely sure why that is. It feels like it might be a bug, but I need to do a bit more research before filing an issue about it on NuGet/Home.

**Comment by adamralph** [comment]
This is on the 1.0.0 milestone for now, but I don't think it's required for RTM, so if it's not resolved before RC, we'll remove the milestone.

**Comment by adamralph** [comment]
Note: if this doesn't make it into 1.0.0, it should be labelled as an [enhancement](https://github.com/adamralph/min-ver/labels/enhancement) for a future version.

**Comment by bording** [comment]
I've spent some more time looking at this, and it turns out the condition I was using for checking for design-time builds was the culprit. I was using a condition that "should" work for both SDK-style and legacy project systems, but the legacy part of the condition was causing it to fail.

I've opened #58 to go ahead and prevent the targets from being run in design-time builds for SDK-style projects.
