### ISSUE TITLE
Minver doesn't work with the legacy project format

### ISSUE THREAD

**Issue by bording** [adamralph/min-ver#59]
While investigating stuff for #55, I realized that MinVer currently only works when using it with an SDK-style project.

The reason is that SDK-style projects will generate all of the assembly version attributes for you based on the `Version` MSBuild property.

Legacy projects don't do that, so the version doesn't propagate to the assembly at all. If we wanted to support this, we'd have to generate a .cs file with all of the required attributes.

Otherwise, you could just document SDK-style projects as another requirement and then nothing else needs to be done. It might be a good idea to add something to the targets file that would actually cause a build warning/error if it's detected it's being used from a legacy project, instead of it just silently not doing anything.

Relates to #3.

**Comment by adamralph** [comment]
@bording thanks for spotting this.

> Otherwise, you could just document SDK-style projects as another requirement and then nothing else needs to be done. It might be a good idea to add something to the targets file that would actually cause a build warning/error if it's detected it's being used from a legacy project, instead of it just silently not doing anything.

I'm favouring this. I think it's reasonable to support only SDK style projects. Do you know a reliable way to detect legacy?

**Comment by bording** [comment]
>  Do you know a reliable way to detect legacy?

As of, I believe, the .NET Core 2.0 SDK, there is a `UsingMicrosoftNETSdk` MSBuild property that will be true for SDK-style projects.

And if you need to know the exact SDK version, you can use `NETCoreSdkVersion`, though I believe that was only added as of .NET Core 2.1.
