### ISSUE TITLE
"runtimes" folder isn't a valid TFM

### ISSUE THREAD

**Issue by bording** [adamralph/min-ver#64]
I'm not sure if this causes any actual problem or not, but the current folder structure of the package might not be ideal:

![image](https://user-images.githubusercontent.com/753669/47880370-71c2ff00-ddf9-11e8-91fc-d92159e2988d.png)

NuGet expects folders underneath the `build` folder to be valid TFMs.

It might be worth moving all of the MinVer.Cli bits into a new `MinVer` root folder in the package, and then update the path in MinVer.targets to be aware of the change.

**Comment by bording** [comment]
@adamralph I was looking at alpha 10 in NuGet Package Explorer and noticed the following:

![image](https://user-images.githubusercontent.com/753669/47942681-27a94e80-dec9-11e8-954f-499ed705f2a1.png)

It turns out that as part of the .NET Core Global Tool work, the tools folder also expects subfolders to be TFMs! 

Again, not sure if this would actually be a real problem (and possibly only if the PackageType metadata indicates it is a tool package), but I'm still wondering if a top-level `MinVer` folder would be a better idea, just to avoid any potential complications.

**Comment by adamralph** [comment]
Ah, yes, that is less than ideal. Perhaps a custom folder is indeed best. One more thought though: what if we acknowledge that the CLI is .NET Core 2.1 app and put it in a tools TFM folder? NPE seems to like it:

<img src="https://user-images.githubusercontent.com/677704/47945000-432f4c00-deff-11e8-968e-fc5fed43aeee.png" width="302px" />

**Comment by bording** [comment]
That does seem like it might work, but I wonder if it's a good idea to put things in that folder structure when it's not actually a global tool?

**Comment by adamralph** [comment]
Perhaps it's not the best idea. The [best documentation I've found so far](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#creating-the-nuspec-file) says:

> Folder | Description | Action upon package install
> -- | -- | --
> tools | Powershell scripts and programs accessible from the Package Manager Console | The tools folder is added to the PATH environment variable for the Package Manager Console only (Specifically, not to the PATH as set for MSBuild when building the project).

That implies that all the files in that folder should be suitable to appear in the Package Manager Console's PATH, and I don't think that's the case with this package. It would actually be quite nice to be able to run `dotnet MinVer.Cli.dll` in the Package Manager Console, but it doesn't work because PATH can't be used in that way.

Let's go with your suggestion of a top level MinVer folder then.

**Comment by adamralph** [comment]
Looks good:

<img src="https://user-images.githubusercontent.com/677704/47951446-1dd32a00-df61-11e8-83bc-23cacf9b5f34.png" width="278px" />

**Comment by adamralph** [comment]
Released in [alpha 11(https://www.nuget.org/packages/MinVer/1.0.0-alpha.11).
