### ISSUE TITLE
NU5105 warnings on SDK style project

### ISSUE THREAD

**Issue by Mpdreamz** [adamralph/min-ver#92]
I'm getting the following warning on a repository with no tags and on `master`.

Having added `<MinVerMajorMinor>1.0</MinVerMajorMinor>`

```
C:\Program Files\dotnet\sdk\2.1.400\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(199,5): warning NU5105: The package version '1.0.0-alpha.0.4' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter. This message can be ignored if the package is not intended for older clients. [C:\Projects\elastic\
AssemblyRewriter\AssemblyRewriter\AssemblyRewriter.csproj]
```

https://docs.microsoft.com/en-us/nuget/reference/package-versioning#semantic-versioning-200

Full 2.0 SemVer support seems quite new, how do I enforce e.g a `-alpha<datestring>`

**Comment by Mpdreamz** [comment]
```
    <MinVerMajorMinor>1.0</MinVerMajorMinor>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerPrerelease>alpha</MinVerPrerelease>
    <MINVER_BUILD_METADATA>$(MinVerPrerelease)$([System.DateTime]::UtcNow.ToString(yyyyMMddTHHmmss))</MINVER_BUILD_METADATA>
```

Produces `1.0.0-alpha.0.4+alpha20181108T115014` as expected but I am trying to find a way to generate

`1.0.0-alpha20181108T115014`

**Comment by adamralph** [comment]
Hi, @Mpdreamz, thanks for raising this. Regarding the warning, the idea is that if you don't care about that, you should suppress the warning: https://github.com/adamralph/simple-exec/blob/ec943f1c19e09b72fe8265929bd0437e0b7e8a3d/SimpleExec/SimpleExec.csproj#L9

Regarding your desired versioning scheme, I can't immediately think of a way to achieve that in the current alpha. I'm offline for the next few days but I'll give it some thought and get back to you next week.

**Comment by adamralph** [comment]
@Mpdreamz before we invest too much further in this, are you 100% sure you can't use a SemVer 2.0 version number? SemVer 2.0 has been supported for well over a year in all the major clients:

| Client                                    | Released |
|-------------------------------------------|----------|
| NuGet 4.3.0+                              | Aug 17   |
| Visual Studio 2017 version 15.3+          | Sep 17   |
| Visual Studio 2015 with NuGet VSIX v3.6.0 | Sep 17   |
| .NET SDK 2.0.0+                           | Aug 17   |
| JetBrains Rider                           | Aug 17   |
| Paket version 5.0+                        | Jun 17   |

Also, MinVer requires [.NET Core SDK 2.1.300 or later](https://github.com/adamralph/min-ver#prerequisites) to be installed on the machine, which kind of makes it a moot point, since you'd have to be running a strange (perhaps even impossible?) combination of old and new for it not to work.

**Comment by Mpdreamz** [comment]
I am not 100÷ certain, please don't spent too much time on this :)

I was exploring using minver as a replacement without impacting our current versioning. 

I much rather spent time moving to semver 2.0 CI versions though. 

I would like to control e.g alpha/beta/rc labels on a branch as well which I don't think is currently possible either or am I missing something? Happy to open a new ticket if not.

**Comment by adamralph** [comment]
> I much rather spent time moving to semver 2.0 CI versions though.

OK, so I guess that means this issue can be closed (please re-open if not). One of the conscious design decisions for MinVer was to use SemVer 2.0 features, specifically to avoid number padding in the pre-release part (e.g. `alpha-0001`) and to avoid embedding build metadata in the pre-release part (e.g. the timestamp in your example).

Theoretically MinVer could have an option to put all that back into the pre-release part, e.g. `1.0.0-{pre-release identifiers}-{padded height}-{build metadata}`, but it's quite ugly, and it would mean having to suppress build metadata for RTM versions. Unless someone can provide a compelling reason to support SemVer 1.0, I don't think this is worth doing.

> I would like to control e.g alpha/beta/rc labels on a branch as well which I don't think is currently possible either or am I missing something? Happy to open a new ticket if not.

After the first tag on that branch, any pre-release identifiers it contains will be propagated to the subsequent interim builds. So one option is to just live with the pre-release identifiers inherited from the base branch (e.g. `alpha.{x}`) until you tag a commit in the current branch with `beta.1`, `rc.1`, etc.

One thing I am also considering is the addition of an MSBuild property that controls the _default_ pre-release phase. Currently it's `alpha` for all branches, but with that property you could change it to `beta` or `rc` on a specific branch by committing a change to the project file. If that's something you'd like to see then yes, please go ahead and open a new issue. Until now, I've been in two minds over whether it's really required.
